rerun-triggers: ['mtime', 'params', 'input', 'software-env', 'code']
notemp: true
printshellcmds: true
keep-going: true
resources: ['network_connections=3', 'mem_mb=8000']
use-conda: true
conda-frontend: 'mamba'
config:
  - 'USE_CUDA=0'
  - 'MAX_THREADS=24'
  - 'jupyter_port=8888'
  - 'server_port=8889'
