rerun-triggers: ['mtime', 'params', 'input', 'software-env', 'code']
notemp: true
printshellcmds: true
keep-going: true
resources: ['network_connections=3', 'mem_mb=500000']
use-conda: true
conda-frontend: 'conda'
use-singularity: false

config:
  - 'USE_CUDA=0'
  - 'MAX_THREADS=8'
  - 'jupyter_port=8828'
  - 'server_port=8829'

set-resources:
    trimmomatic_paired:
        mem: 8GB
